/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 *
 * Answer: 4613732
 */

function findSumOfEvenFibonacciTerms(max){
   var beforeLast=1;
   var last=2;
   var current=3;
   var sum=2;

   while(current < max){
      current=beforeLast+last;
      beforeLast=last;
      last=current;
      if(!(current%2)){
         sum += current;
      }
   }
   return sum;
}